In [1]:
from zipfile import ZipFile
from urllib.request import urlopen   
import pandas as pd
import numpy as np
import requests
import os
import glob
from os import walk
from bs4 import BeautifulSoup

In [2]:
Links_2013 = ['https://s3.amazonaws.com/tripdata/201801-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201802-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201803-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201804-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201805-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201806-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201807-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201808-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201809-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201810-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201811-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201812-citibike-tripdata.csv.zip',\
       ]

Links_2018 = ['https://s3.amazonaws.com/tripdata/201801-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201802-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201803-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201804-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201805-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201806-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201807-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201808-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201809-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201810-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201811-citibike-tripdata.csv.zip',\
        'https://s3.amazonaws.com/tripdata/201812-citibike-tripdata.csv.zip',\
       ]

In [42]:
links = []
path = 'https://s3.amazonaws.com/tripdata/'
year_start = 2013
year_end = 2020
for y in range(year_start, year_end, 1):
    i = 1
    j = 13
    
    if y == 2013:
        i = 6
        
    if y == 2019:
        j = 10
      
    csv_name = ''
    if y > 2016:
        csv_name = '.csv'
    
    for m in range(i, j, 1):
        s = '0'
        if m > 9:
          s = ''
        links.append(f'{path}{y}{s}{m}-citibike-tripdata{csv_name}.zip')  

links.append(path + '201307-201402-citibike-tripdata.zip')
links.append(path + '201611-citibike-tripdata 23-17-16-417.zip')
links.append(path + '201702-citibike-tripdata.csv 23-17-18-428.zip')
links.append(path + '201704-citibike-tripdata.csv 23-17-24-762.zip')
links.append(path + '201810-citibike-tripdata.csv 23-18-13-331.zip')

print(links)

['https://s3.amazonaws.com/tripdata/201306-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201307-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201308-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201309-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201310-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201311-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201312-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201401-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201402-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201403-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201404-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201405-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201406-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201407-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201408-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201409-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201410-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201411-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201412-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201501-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201502-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201503-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201504-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201505-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201506-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201507-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201508-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201509-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201510-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201511-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201512-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201601-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201602-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201603-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201604-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201605-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201606-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201607-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201608-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201609-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201610-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201611-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201612-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201701-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201702-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201703-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201704-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201705-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201706-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201707-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201708-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201709-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201710-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201711-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201712-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201801-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201802-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201803-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201804-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201805-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201806-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201807-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201808-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201809-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201810-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201811-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201812-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201901-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201902-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201903-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201904-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201905-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201906-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201907-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201908-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201909-citibike-tripdata.csv.zip', 'https://s3.amazonaws.com/tripdata/201307-201402-citibike-tripdata.zip', 'https://s3.amazonaws.com/tripdata/201611-citibike-tripdata 23-17-16-417.zip', 'https://s3.amazonaws.com/tripdata/201702-citibike-tripdata.csv 23-17-18-428.zip', 'https://s3.amazonaws.com/tripdata/201704-citibike-tripdata.csv 23-17-24-762.zip', 'https://s3.amazonaws.com/tripdata/201810-citibike-tripdata.csv 23-18-13-331.zip']

In [ ]:
rides = []
for link in links:
    try:
        df = pd.read_csv(link)
        rides.append(df)            
    except: continue  
        
rides_df = pd.concat(rides)

/Users/olgataranukha/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

In [ ]:
rides_df.describe()

In [39]:
rides_df.tail()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
443961,1014,2013-12-31 23:55:56,2014-01-01 00:12:50,350,Clinton St & Grand St,40.715595,-73.987030,532,S 5 Pl & S 4 St,40.710451,-73.960876,16336,Subscriber,1973,1
443962,682,2013-12-31 23:57:04,2014-01-01 00:08:26,538,W 49 St & 5 Ave,40.757952,-73.977876,2006,Central Park S & 6 Ave,40.765909,-73.976342,18352,Subscriber,1986,1
443963,1520,2013-12-31 23:57:44,2014-01-01 00:23:04,281,Grand Army Plaza & Central Park S,40.764397,-73.973715,411,E 6 St & Avenue D,40.722281,-73.976687,15000,Subscriber,1985,1
443964,1166,2013-12-31 23:58:14,2014-01-01 00:17:40,492,W 33 St & 7 Ave,40.750200,-73.990931,253,W 13 St & 5 Ave,40.735439,-73.994539,21022,Subscriber,1955,1
443965,677,2013-12-31 23:58:16,2014-01-01 00:09:33,463,9 Ave & W 16 St,40.742065,-74.004432,448,W 37 St & 10 Ave,40.756604,-73.997901,17559,Subscriber,1986,1

In [ ]:
rides_df.to_csv('Resources/Citibike_rides.csv', encoding='utf-8', index=False)

In [3]:
# y = '2013'
# m = '06'
# df_test = pd.read_csv(f'https://s3.amazonaws.com/tripdata/{y}{m}-citibike-tripdata.csv.zip')

In [4]:
df_test.describe()

,tripduration,start station id,start station latitude,start station longitude,end station id,end station latitude,end station longitude,bikeid,birth year,gender
count,7.189940e+05,718994.000000,718994.000000,718994.000000,718994.000000,718994.000000,718994.000000,718994.000000,718994.000000,718994.000000
mean,8.268107e+02,1469.519095,40.737894,-73.982934,1460.948474,40.737620,-73.983203,26078.046315,1977.765945,1.169969
std,3.279694e+04,1398.626487,0.044702,0.018219,1396.759046,0.044525,0.018273,6311.931441,12.016931,0.472668
min,6.100000e+01,72.000000,40.646538,-74.017134,72.000000,40.646538,-74.033552,14529.000000,1885.000000,0.000000
25%,3.190000e+02,377.000000,40.719079,-73.994685,376.000000,40.719105,-73.994758,19558.000000,1969.000000,1.000000
50%,5.100000e+02,497.000000,40.739355,-73.985649,497.000000,40.739323,-73.986580,28538.000000,1980.000000,1.000000
75%,8.420000e+02,3170.000000,40.756687,-73.974987,3169.000000,40.756405,-73.975232,31571.000000,1988.000000,1.000000
max,1.951005e+07,3664.000000,45.506364,-73.568906,3664.000000,45.506364,-73.568906,33522.000000,2002.000000,2.000000

In [5]:
df_test.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,970,2018-01-01 13:50:57.4340,2018-01-01 14:07:08.1860,72,W 52 St & 11 Ave,40.767272,-73.993929,505,6 Ave & W 33 St,40.749013,-73.988484,31956,Subscriber,1992,1
1,723,2018-01-01 15:33:30.1820,2018-01-01 15:45:33.3410,72,W 52 St & 11 Ave,40.767272,-73.993929,3255,8 Ave & W 31 St,40.750585,-73.994685,32536,Subscriber,1969,1
2,496,2018-01-01 15:39:18.3370,2018-01-01 15:47:35.1720,72,W 52 St & 11 Ave,40.767272,-73.993929,525,W 34 St & 11 Ave,40.755942,-74.002116,16069,Subscriber,1956,1
3,306,2018-01-01 15:40:13.3720,2018-01-01 15:45:20.1910,72,W 52 St & 11 Ave,40.767272,-73.993929,447,8 Ave & W 52 St,40.763707,-73.985162,31781,Subscriber,1974,1
4,306,2018-01-01 18:14:51.5680,2018-01-01 18:19:57.6420,72,W 52 St & 11 Ave,40.767272,-73.993929,3356,Amsterdam Ave & W 66 St,40.774667,-73.984706,30319,Subscriber,1992,1

In [7]:
# df_list=[]
# for Link in Links:
# # open and save the zip file onto computer
#     url = urlopen(Link)
#     output = open('zipFile.zip', 'wb')           
#     output.write(url.read())
#     output.close()

# # read the zip file as a pandas dataframe
#     df = pd.read_csv('zipFile.zip')      
#     df_list.append(df)

# df = pd.concat(df_list)
# df

# df.to_csv('Resources/Citibike_2018.csv', encoding='utf-8', index=False)

In [20]:
citibike_rides_df = pd.concat([pd.read_csv(link) for link in Links], ignore_index = True)
citibike_rides_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,970,2018-01-01 13:50:57.4340,2018-01-01 14:07:08.1860,72.0,W 52 St & 11 Ave,40.767272,-73.993929,505.0,6 Ave & W 33 St,40.749013,-73.988484,31956,Subscriber,1992,1
1,723,2018-01-01 15:33:30.1820,2018-01-01 15:45:33.3410,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3255.0,8 Ave & W 31 St,40.750585,-73.994685,32536,Subscriber,1969,1
2,496,2018-01-01 15:39:18.3370,2018-01-01 15:47:35.1720,72.0,W 52 St & 11 Ave,40.767272,-73.993929,525.0,W 34 St & 11 Ave,40.755942,-74.002116,16069,Subscriber,1956,1
3,306,2018-01-01 15:40:13.3720,2018-01-01 15:45:20.1910,72.0,W 52 St & 11 Ave,40.767272,-73.993929,447.0,8 Ave & W 52 St,40.763707,-73.985162,31781,Subscriber,1974,1
4,306,2018-01-01 18:14:51.5680,2018-01-01 18:19:57.6420,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3356.0,Amsterdam Ave & W 66 St,40.774667,-73.984706,30319,Subscriber,1992,1
5,1602,2018-01-01 21:31:54.1920,2018-01-01 21:58:36.3530,72.0,W 52 St & 11 Ave,40.767272,-73.993929,482.0,W 15 St & 7 Ave,40.739355,-73.999318,30106,Subscriber,1968,1
6,722,2018-01-02 07:54:53.6460,2018-01-02 08:06:55.8720,72.0,W 52 St & 11 Ave,40.767272,-73.993929,228.0,E 48 St & 3 Ave,40.754601,-73.971879,32059,Subscriber,1978,1
7,434,2018-01-02 08:06:14.3310,2018-01-02 08:13:28.7670,72.0,W 52 St & 11 Ave,40.767272,-73.993929,173.0,Broadway & W 49 St,40.760683,-73.984527,30525,Subscriber,1983,1
8,366,2018-01-02 08:10:15.2550,2018-01-02 08:16:21.8960,72.0,W 52 St & 11 Ave,40.767272,-73.993929,479.0,9 Ave & W 45 St,40.760193,-73.991255,27439,Subscriber,1974,1
9,324,2018-01-02 08:13:30.8960,2018-01-02 08:18:55.1200,72.0,W 52 St & 11 Ave,40.767272,-73.993929,450.0,W 49 St & 8 Ave,40.762272,-73.987882,30892,Subscriber,1947,1
10,1155,2018-01-02 09:15:29.9050,2018-01-02 09:34:45.0200,72.0,W 52 St & 11 Ave,40.767272,-73.993929,347.0,Greenwich St & W Houston St,40.728846,-74.008591,31591,Subscriber,1982,1
11,1200,2018-01-02 10:23:18.8800,2018-01-02 10:43:18.9110,72.0,W 52 St & 11 Ave,40.767272,-73.993929,127.0,Barrow St & Hudson St,40.731724,-74.006744,30257,Subscriber,1974,1
12,732,2018-01-02 11:52:37.5540,2018-01-02 12:04:49.8800,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3635.0,W 36 St & 9 Ave,40.754623,-73.995168,32649,Subscriber,1969,1
13,600,2018-01-02 12:20:57.0070,2018-01-02 12:30:57.0180,72.0,W 52 St & 11 Ave,40.767272,-73.993929,457.0,Broadway & W 58 St,40.766953,-73.981693,26964,Subscriber,1991,1
14,1058,2018-01-02 13:28:46.1540,2018-01-02 13:46:24.3070,72.0,W 52 St & 11 Ave,40.767272,-73.993929,523.0,W 38 St & 8 Ave,40.754666,-73.991382,32617,Subscriber,1947,1
15,256,2018-01-02 13:54:11.6460,2018-01-02 13:58:28.1980,72.0,W 52 St & 11 Ave,40.767272,-73.993929,514.0,12 Ave & W 40 St,40.760875,-74.002777,31095,Subscriber,1978,1
16,318,2018-01-02 13:55:11.9200,2018-01-02 14:00:29.9410,72.0,W 52 St & 11 Ave,40.767272,-73.993929,478.0,11 Ave & W 41 St,40.760301,-73.998842,31182,Subscriber,1963,1
17,694,2018-01-02 14:27:49.6230,2018-01-02 14:39:24.1270,72.0,W 52 St & 11 Ave,40.767272,-73.993929,484.0,W 44 St & 5 Ave,40.755003,-73.980144,32375,Subscriber,1967,1
18,604,2018-01-02 15:04:41.3810,2018-01-02 15:14:45.7090,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3635.0,W 36 St & 9 Ave,40.754623,-73.995168,32505,Subscriber,1964,1
19,724,2018-01-02 15:25:00.5410,2018-01-02 15:37:05.3230,72.0,W 52 St & 11 Ave,40.767272,-73.993929,490.0,8 Ave & W 33 St,40.751551,-73.993934,19512,Subscriber,1965,1
20,395,2018-01-02 15:37:55.9310,2018-01-02 15:44:31.0550,72.0,W 52 St & 11 Ave,40.767272,-73.993929,514.0,12 Ave & W 40 St,40.760875,-74.002777,17881,Subscriber,1956,1
21,520,2018-01-02 16:09:21.1800,2018-01-02 16:18:02.0510,72.0,W 52 St & 11 Ave,40.767272,-73.993929,500.0,Broadway & W 51 St,40.762288,-73.983362,31426,Customer,1969,0
22,430,2018-01-02 16:10:59.3790,2018-01-02 16:18:10.0110,72.0,W 52 St & 11 Ave,40.767272,-73.993929,500.0,Broadway & W 51 St,40.762288,-73.983362,32349,Customer,1969,0
23,842,2018-01-02 16:34:16.2920,2018-01-02 16:48:18.6180,72.0,W 52 St & 11 Ave,40.767272,-73.993929,490.0,8 Ave & W 33 St,40.751551,-73.993934,31019,Subscriber,1978,1
24,243,2018-01-02 16:36:12.6120,2018-01-02 16:40:15.7660,72.0,W 52 St & 11 Ave,40.767272,-73.993929,479.0,9 Ave & W 45 St,40.760193,-73.991255,29984,Subscriber,1973,1
25,705,2018-01-02 16:36:14.3160,2018-01-02 16:47:59.7340,72.0,W 52 St & 11 Ave,40.767272,-73.993929,477.0,W 41 St & 8 Ave,40.756405,-73.990026,20922,Subscriber,1992,1
26,1163,2018-01-02 16:43:09.9290,2018-01-02 17:02:33.2530,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3466.0,W 45 St & 6 Ave (OLD),40.756687,-73.982577,33277,Subscriber,1974,1
27,680,2018-01-02 16:58:34.7080,2018-01-02 17:09:55.0030,72.0,W 52 St & 11 Ave,40.767272,-73.993929,490.0,8 Ave & W 33 St,40.751551,-73.993934,16425,Subscriber,1964,1
28,634,2018-01-02 17:04:25.6190,2018-01-02 17:14:59.7750,72.0,W 52 St & 11 Ave,40.767272,-73.993929,484.0,W 44 St & 5 Ave,40.755003,-73.980144,28382,Subscriber,1977,1
29,782,2018-01-02 17:13:04.4750,2018-01-02 17:26:06.8250,72.0,W 52 St & 11 Ave,40.767272,-73.993929,3255.0,8 Ave & W 31 St,40.750585,-73.994685,30649,Subscriber,1982,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17548309,206,2018-12-31 23:30:09.5760,2018-12-31 23:33:36.5100,390.0,Duffield St & Willoughby St,40.692216,-73.984284,243.0,Fulton St & Rockwell Pl,40.688226,-73.979382,27440,Subscriber,1985,2
17548310,924,2018-12-31 23:30:41.7490,2018-12-31 23:46:06.7030,446.0,W 24 St & 7 Ave,40.744876,-73.995299,516.0,E 47 St & 1 Ave,40.752069,-73.967844,34663,Subscriber,1980,1
17548311,426,2018-12-31 23:32:07.9720,2018-12-31 23:39:14.3750,368.0,Carmine St & 6 Ave,40.730386,-74.002150,146.0,Hudson St & Reade St,40.716250,-74.009106,34329,Subscriber,1999,1
17548312,247,2018-12-31 23:32:26.2510,2018-12-31 23:36:34.0940,383.0,Greenwich Ave & Charles St,40.735238,-74.000271,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,32671,Subscriber,1989,1
17548313,282,2018-12-31 23:32:30.8410,2018-12-31 23:37:13.3520,383.0,Greenwich Ave & Charles St,40.735238,-74.000271,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,15624,Subscriber,1988,1
17548314,245,2018-12-31 23:35:10.8400,2018-12-31 23:39:16.6350,3136.0,5 Ave & E 63 St,40.766368,-73.971518,3137.0,5 Ave & E 73 St,40.772828,-73.966853,26633,Subscriber,1961,1
17548315,516,2018-12-31 23:35:37.7230,2018-12-31 23:44:14.4130,128.0,MacDougal St & Prince St,40.727103,-74.002971,308.0,St James Pl & Oliver St,40.713079,-73.998512,19088,Subscriber,1984,1
17548316,588,2018-12-31 23:36:25.3260,2018-12-31 23:46:13.6530,3397.0,Court St & Nelson St,40.676395,-73.998699,143.0,Clinton St & Joralemon St,40.692395,-73.993379,15107,Subscriber,1964,1
17548317,306,2018-12-31 23:36:51.0920,2018-12-31 23:41:57.3660,82.0,St James Pl & Pearl St,40.711174,-74.000165,340.0,Madison St & Clinton St,40.712690,-73.987763,15864,Subscriber,1995,1
17548318,927,2018-12-31 23:37:03.8570,2018-12-31 23:52:31.7830,3151.0,E 81 St & York Ave,40.772838,-73.949892,3137.0,5 Ave & E 73 St,40.772828,-73.966853,35203,Customer,1998,1
17548319,94,2018-12-31 23:37:27.7690,2018-12-31 23:39:02.0710,360.0,William St & Pine St,40.707179,-74.008873,376.0,John St & William St,40.708621,-74.007222,31001,Subscriber,1991,1
17548320,1161,2018-12-31 23:38:29.4360,2018-12-31 23:57:51.3750,495.0,W 47 St & 10 Ave,40.762699,-73.993012,281.0,Grand Army Plaza & Central Park S,40.764397,-73.973715,16078,Subscriber,1969,0
17548321,1015,2018-12-31 23:39:10.7270,2018-12-31 23:56:06.6920,379.0,W 31 St & 7 Ave,40.749156,-73.991600,301.0,E 2 St & Avenue B,40.722174,-73.983688,34170,Subscriber,1985,1
17548322,776,2018-12-31 23:41:17.7150,2018-12-31 23:54:13.9450,532.0,S 5 Pl & S 5 St,40.710451,-73.960876,307.0,Canal St & Rutgers St,40.714275,-73.989900,34093,Subscriber,1988,2
17548323,588,2018-12-31 23:41:14.4590,2018-12-31 23:51:02.5500,195.0,Liberty St & Broadway,40.709056,-74.010434,534.0,Water - Whitehall Plaza,40.702551,-74.012723,35081,Subscriber,1980,1
17548324,71,2018-12-31 23:42:57.9190,2018-12-31 23:44:09.2080,3367.0,5 Ave & E 103 St,40.792255,-73.952499,3367.0,5 Ave & E 103 St,40.792255,-73.952499,27026,Subscriber,1955,1
17548325,217,2018-12-31 23:43:10.0890,2018-12-31 23:46:47.4740,314.0,Cadman Plaza West & Montague St,40.693830,-73.990539,391.0,Clark St & Henry St,40.697601,-73.993446,27452,Subscriber,1965,1
17548326,385,2018-12-31 23:45:45.7440,2018-12-31 23:52:10.9330,3429.0,Hanson Pl & Ashland Pl,40.685068,-73.977908,3637.0,Fulton St & Waverly Ave,40.683239,-73.965996,33086,Subscriber,1973,1
17548327,651,2018-12-31 23:46:44.4210,2018-12-31 23:57:35.9100,3295.0,Central Park W & W 96 St,40.791270,-73.964839,3165.0,Central Park West & W 72 St,40.775794,-73.976206,32449,Subscriber,1969,0
17548328,620,2018-12-31 23:47:10.2080,2018-12-31 23:57:30.6020,3295.0,Central Park W & W 96 St,40.791270,-73.964839,3165.0,Central Park West & W 72 St,40.775794,-73.976206,15699,Customer,1989,2
17548329,798,2018-12-31 23:49:37.0590,2019-01-01 00:02:55.1640,518.0,E 39 St & 2 Ave,40.747804,-73.973442,3709.0,W 15 St & 6 Ave,40.738046,-73.996430,35603,Subscriber,1982,1
17548330,312,2018-12-31 23:49:43.9520,2018-12-31 23:54:56.2510,3166.0,Riverside Dr & W 72 St,40.780578,-73.985624,3164.0,Columbus Ave & W 72 St,40.777057,-73.978985,27419,Subscriber,1960,1
17548331,165,2018-12-31 23:50:34.6070,2018-12-31 23:53:20.5830,498.0,Broadway & W 32 St,40.748549,-73.988084,472.0,E 32 St & Park Ave,40.745712,-73.981948,20190,Subscriber,1994,2
17548332,1027,2018-12-31 23:51:13.9220,2019-01-01 00:08:21.7900,423.0,W 54 St & 9 Ave,40.765849,-73.986905,285.0,Broadway & E 14 St,40.734546,-73.990741,28510,Subscriber,1981,1
17548333,174,2018-12-31 23:53:59.0720,2018-12-31 23:56:53.4750,260.0,Broad St & Bridge St,40.703652,-74.011678,260.0,Broad St & Bridge St,40.703652,-74.011678,33887,Subscriber,1980,1
17548334,734,2018-12-31 23:55:06.9910,2019-01-01 00:07:21.2300,336.0,Sullivan St & Washington Sq,40.730477,-73.999061,379.0,W 31 St & 7 Ave,40.749156,-73.991600,27111,Subscriber,1986,1
17548335,2551,2018-12-31 23:55:44.3070,2019-01-01 00:38:15.7820,3320.0,Central Park West & W 100 St,40.794067,-73.962868,2006.0,Central Park S & 6 Ave,40.765909,-73.976342,16390,Customer,1969,0
17548336,2376,2018-12-31 23:56:52.8500,2019-01-01 00:36:29.2860,427.0,Bus Slip & State St,40.701907,-74.013942,259.0,South St & Whitehall St,40.701221,-74.012342,34398,Subscriber,1979,1
17548337,2758,2018-12-31 23:58:29.2120,2019-01-01 00:44:27.5170,3320.0,Central Park West & W 100 St,40.794067,-73.962868,281.0,Grand Army Plaza & Central Park S,40.764397,-73.973715,30818,Customer,1969,0
17548338,2459,2018-12-31 23:59:51.0850,2019-01-01 00:40:50.8800,128.0,MacDougal St & Prince St,40.727103,-74.002971,402.0,Broadway & E 22 St,40.740343,-73.989551,34775,Subscriber,1996,2

In [21]:
citibike_rides_df.to_csv('Resources/Citibike_2018.csv', encoding='utf-8', index=False)

In [13]:
# df = pd.read_csv('https://s3.amazonaws.com/tripdata/201801-citibike-tripdata.csv.zip')
# df.head(10)

In [7]:
# path = 'https://s3.amazonaws.com/tripdata/index.html'
# for f in glob.glob(path):
#     print(f)

In [22]:
# path of zip files
# path = 'Resources/*.*'
# for f in glob.glob(path):
#     print(f)

# citibike_rides_df = pd.concat([pd.read_csv(f) for f in glob.glob(path)], ignore_index = True)

# citibike_rides_df = pd.concat([pd.read_csv(f) for f in glob.glob(path)], ignore_index = True)

# print(glob.glob(path))
# for f in os.walk(path):
#     print(f)
# files = []
# # r=root, d=directories, f = files
# for r, d, f in os.walk(path):
#     for file in f:
#         if '.zip' in file:
#             files.append(os.path.join(r, file))

# for f in files:
#     print(f)
# import glob
# glob.glob()

# folders = [f for f in glob.glob(path + "**/", recursive=True)]

# for f in folders:
#     print(f)

In [4]:
# from urllib.request import Request, urlopen, urlretrieve
from bs4 import BeautifulSoup
def read_url(url):
#     url = url.replace(" ","%20")
#     req = requests.get(url)
    a = urlopen(url).read()
    print(a)
    soup = BeautifulSoup(a, 'html.parser')
    files = (soup.find_all('Key'))
    print(files)
    for f in files:
        file_name = f.extract().get_text()
        print(file_name)
#         url_new = url + file_name
#         url_new = url_new.replace(" ","%20")
#         if(file_name[-1]=='/' and file_name[0]!='.'):
#             read_url(url_new)
#         print(url_new)

 read_url("https://s3.amazonaws.com/tripdata/")

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 20)

In [27]:
# path of zip files
path = 'https://s3.amazonaws.com/tripdata'
for f in glob.glob(path):
    df=pd.read_csv(f)
    df.head(10)

#citibike_rides_df = pd.concat([pd.read_csv(f) for f in glob.glob(path)], ignore_index = True)
# citibike_rides_df = pd.concat([pd.read_csv(f) for f in os.listdir(path)], ignore_index = True)
# for filename in os.listdir(path):
#     citibike_rides_df = pd.concat([pd.read_csv(f) for f in os.listdir(path)], ignore_index = True)
#     df = pd.read_csv('filename.zip', compression='zip', header=0, sep=',', quotechar='"')
#     url = urlopen(Link)
#     output = open('zipFile.zip', 'wb')           
#     output.write(url.read())
#     output.close()

# # read the zip file as a pandas dataframe
#     df = pd.read_csv('zipFile.zip')      
#     df_list.append(df)

In [ ]:
from io import BytesIO
from zipfile import ZipFile
import pandas
import requests

url = "https://www.nseindia.com/content/indices/mcwb_jun19.zip"
content = requests.get(url)
zf = ZipFile(BytesIO(content.content))

for item in zf.namelist():
    print("File in zip: "+  item)

# find the first matching csv file in the zip:
match = [s for s in zf.namelist() if ".csv" in s][0]
# the first line of the file contains a string - that line shall de     ignored, hence skiprows
df = pandas.read_csv(zf.open(match), low_memory=False, skiprows=[0])

In [10]:
# path of zip files
zipFileURL = 'https://s3.amazonaws.com/tripdata'

# retrieve list of URLs from the webservers
url = urlopen(zipFileURL)
usock = urllib.urlopen(zipFileURL)
parser = urllister.URLLister()
parser.feed(usock.read())
usock.close()
parser.close()

# only parse urls
for url in parser.urls: 
    citibike_rides_df = pd.concat([pd.read_csv(url)], ignore_index = True)

NameError: name 'urllib' is not defined

In [ ]:
from urllib.request import Request, urlopen, urlretrieve
from bs4 import BeautifulSoup
def read_url(url):
    url = url.replace(" ","%20")
    req = Request(url)
    a = urlopen(req).read()
    soup = BeautifulSoup(a, 'html.parser')
    x = (soup.find_all('a'))
    for i in x:
        file_name = i.extract().get_text()
        print(file_name)
#         url_new = url + file_name
#         url_new = url_new.replace(" ","%20")
#         if(file_name[-1]=='/' and file_name[0]!='.'):
#             read_url(url_new)
#         print(url_new)

read_url("www.example.com")

In [ ]:
# citibike_rides = pd.concat([pd.read_csv(f) for f in os.walk('raw_data/CitiBikeDailyRidershipandMembershipData/*.csv')], ignore_index = True)
# citibike_trips = pd.concat([pd.read_csv(f) for f in os.walk('raw_data/CitiBikeTripHistories/*.csv')], ignore_index = True)

In [ ]:
# citibike_rides = pd.concat([pd.read_csv(f) for f in glob.glob('raw_data/CitiBikeDailyRidershipandMembershipData/*.csv')], ignore_index = True)
# citibike_trips = pd.concat([pd.read_csv(f) for f in glob.glob('raw_data/CitiBikeTripHistories/*.csv')], ignore_index = True)